### PR TITLE
Issue 58

### LINKED ISSUE #58: Http Server: threads created in transactions increase activeCount and server will eventually stop processing requests
We have the problem, that the http server sometimes becomes irresponsive. I tracked it down to the following:
 Transactions are no longer processed if the activeCount of the TransactionManager is higher than the configured maximum (in run method of the SocketListener). If a new thread is created during a transaction, it adds to this count because its parent is the worker thread which is in the TransactionManager group. If more threads are generated, the limit can be hit although this is not representing that (too) many transactions are queued (which i believe is the idea behind the limit).
The problem can be avoided by explicitly setting the thread group of threads created during calls but i don't think anyone will be aware of the problem and do it.
I propose that activeCount in TransactionManager should not be activeCount of the ThreadGroup but the number of not idle workers (num_workers or size of workers) plus the size of the transQueue. Either by overriding the activeCount method or creating a new one.

### PR DESCRIPTION
**Pull request by d3bjorn**
Http Server: threads created in transactions increase activeCount and server will eventually stop processing requests
https://github.com/knopflerfish/knopflerfish.org/issues/58

### CODE REVIEW

**Review by chlarsson — CHANGES_REQUESTED** [review]
Copyright year should be updated.

Why is there a 
System.out.println("starting up");
in the SocketListener, change to log.info ?

**Comment by d3bjorn** [comment]
> Copyright year should be updated.

I thought I did that. Did I miss some file?

> Why is there a System.out.println("starting up"); in the SocketListener, change to log.info ?

"Someone" put it there in 2015. ;) I guess we could clean up classes that we're editing anyway. I'll fix some obvious things in SocketListener.

**Comment by chlarsson** [comment]
Copyright in the HttpCommandGroup.java wasn't updated

Also change minor version of bundle. I think the fix qualifies for that.

**Comment by d3bjorn** [comment]
Bundle version updated.

Copyright in HttpCommandGroup.java was updated in stringbuffer-to-builder merge.

**Comment by chlarsson** [comment]
Since 5.3.0 is not part of any release, the model in KF has been to only bump bundle versions once inbetween releases, and not for every fix / commit. So I suggest we go should leave it at 5.3.0.

**Review by chlarsson — APPROVED** [review]

**Pull request merged**
