### PR TITLE
Improve framework log message when unable to resolve

### LINKED ISSUE #42: Improve framework log message when unable to resolve
When the framework fails to resolve a package the following error message is written:
[stderr] org.osgi.framework.BundleException: Bundle#7, unable to resolve: Missing package(s) or can not resolve all of the them:
.... package name(s) follows....

Would be preferred if also the bundle name and/or symbolic name can be written in addition to the bundle id. Especially if the number of bundles is large.

### PR DESCRIPTION
**Pull request by d3bjorn**
Improve framework log message when unable to resolve
https://github.com/knopflerfish/knopflerfish.org/issues/42

### CODE REVIEW

**Review by chlarsson — CHANGES_REQUESTED** [review]
This is not the message the issue was referring to, that's in the resolver and refers to missing packagages. Is that error propagated to here?

**Comment by d3bjorn** [comment]
As far as I can see, this is the only place where we say "unable to resolve" in knopflerfish.org.

**Comment by chlarsson** [comment]
OK, but is the underlying problem(s) propagated and logged correctly with this change?

**Comment by d3bjorn** [comment]
I think so. It looks like BundleImpl calls resolvePackages on BundleGeneration, which calls resolvePackages on BundlePackages, which calls the Resolver, and if there is a failReason returned from Resolver, the "unable to resolve" BundleException is thrown with the failReason in its message.

When I run the tests, the framework_test bundle causes this to be logged a few times, which seems to be expected by those tests.

**Comment by d3bjorn** [comment]
Maybe we want to include the bundle name in similar BundleException messages? For example, I found it very useful to include it for "start failed" when investigating test bundles failing to start.

**Comment by chlarsson** [comment]
Sound like a good idea.

Just a quick note - can we be sure the bundle name / symbolic name is always present if a bundle fails to a) resolve or b) fails to start? Or can it be null in certain cases

**Comment by d3bjorn** [comment]
run-kf-tests and osgi_tck looks good after these changes.

**Comment by d3bjorn** [comment]
It looks like the name can be null, but I think that's a rare case and getting "null" would be ok in those cases.
It looks like, in theory, current BundleGeneration could be missing after using the system bundle's BundleImpl constructor, but if that happens BundleImpl would crash very hard before trying to log anything, so I don't think it can actually happen.

**Pull request merged**
